# Generated by Django 4.2.11 on 2026-09-10

from django.db import migrations, models

from obd.core.tournament_categories import CHOICES, OUTROS, adivinhar_categoria


def preencher_categorias(apps, schema_editor):
    """Dá um tipo inicial a cada liga.

    A preferência é copiar do torneio capturado que tenha o mesmo nome, porque lá o
    administrador já escolheu. Quando não existe torneio com aquele nome — caso das
    ligas criadas por importação de planilha, e das que ficaram com o nome antigo
    depois de o torneio ser renomeado no N01 — o chute pelo nome entra no lugar.

    A partir daqui o tipo mora na liga e não depende mais de nome nenhum.
    """
    League = apps.get_model('leagues', 'League')
    TournamentResult = apps.get_model('core', 'TournamentResult')

    por_nome = dict(TournamentResult.objects.values_list('name', 'category'))
    for pk, nome in League.objects.values_list('pk', 'name'):
        categoria = por_nome.get(nome) or adivinhar_categoria(nome)
        League.objects.filter(pk=pk).update(category=categoria)


def desfazer(apps, schema_editor):
    """Nada a desfazer: a coluna inteira sai quando a AddField é revertida."""


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_remove_league_enviroment'),
        # A cópia acima lê TournamentResult.category, que nasce na 0012 de core.
        ('core', '0012_tournament_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='category',
            field=models.CharField(
                'Tipo de Torneio',
                max_length=20,
                choices=CHOICES,
                default=OUTROS,
                help_text='Define em qual bloco do Hall dos Campeões os campeões desta liga '
                          'aparecem. Normalmente vem preenchido do torneio capturado; edite aqui '
                          'quando o nome da liga não for igual ao do torneio.',
            ),
        ),
        migrations.RunPython(preencher_categorias, desfazer),
    ]
