# Generated by Django 3.1.7 on 2021-06-30 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisions', '0004_division_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='finals',
            field=models.ManyToManyField(blank=True, related_name='finals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='playoffs',
            field=models.ManyToManyField(blank=True, related_name='playoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='third',
            field=models.ManyToManyField(blank=True, related_name='third', to=settings.AUTH_USER_MODEL),
        ),
    ]
