# Generated by Django 3.1.7 on 2021-09-29 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('champions', '0002_auto_20210928_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='champion',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='champion',
            name='p3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='champion',
            name='p4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p4', to=settings.AUTH_USER_MODEL),
        ),
    ]
