# Generated by Django 3.1.7 on 2021-03-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210325_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='456168-3', max_length=10, null=True, unique=True),
        ),
    ]
