# Generated by Django 3.1.7 on 2021-03-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210330_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='332791-6', max_length=10, null=True, unique=True),
        ),
    ]
