# Generated by Django 3.1.7 on 2021-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210404_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='590360-9', max_length=10, null=True, unique=True),
        ),
    ]
