# Generated by Django 3.1.7 on 2021-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20210419_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='017602-3', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='djangodbmodelsquery_utilsdeferredattribute-object-at-0x7fa81668c910-djangodbmodelsquery_utilsdeferredattribute-object-at-0x7fa81668c970-djangodbmodelsfieldscharfield', max_length=100, null=True),
        ),
    ]
