# Generated by Django 3.1.7 on 2021-10-06 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixtures', '0010_fixture_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, default=0)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'DERROTA'), (1, 'EMPATE'), (2, 'VITORIA'), (3, 'CAMPEAO'), (4, 'VICE'), (5, 'TERCEIRO'), (6, 'AUTO')], default=6)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
