# Generated by Django 3.1.7 on 2021-10-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merit',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
