# Generated by Django 3.1.7 on 2021-10-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merits', '0002_merit_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merit',
            options={'ordering': ('-created_at',), 'verbose_name': 'merit', 'verbose_name_plural': 'merits'},
        ),
    ]
