# Generated by Django 4.2.11 on 2026-09-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merits', '0004_alter_merit_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merit',
        ),
    ]
