"""
Django settings for obd project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from decouple import config, Csv
import cloudinary
import cloudinary.uploader
import cloudinary.api
import resend

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'true'
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
RESEND_API_KEY = config('RESEND_API_KEY')
resend.api_key = RESEND_API_KEY
LOGIN_URL = '/dashboard/players/dashboard/player/login'

# Endereço do admin do Django. Fica numa variável de ambiente, e não no código, para
# não ser publicado junto com o repositório. Trocar o endereço padrão não deixa o admin
# mais forte — só o tira da mira dos robôs que varrem /admin/ o dia inteiro. Quem
# protege de verdade é o limite de tentativas (core/seguranca.py) e uma senha boa.
# Sem a variável, continua valendo 'admin/', então nada quebra se ela faltar.
_admin_url = config('ADMIN_URL', default='admin').strip().strip('/')
ADMIN_URL = f'{_admin_url or "admin"}/'

# Application definition

INSTALLED_APPS = [
    'scout_apm.django',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'test_without_migrations',
    'django_extensions',
    'obd.core',
    'obd.core.obdlib',
    'obd.core.obdlib.webscraping',
    'obd.dashboards',
    'obd.dashboards.players',
    'obd.dashboards.players.logins',
    'obd.dashboards.players.profiles.apps.ProfileConfig',
    'obd.dashboards.players.stats.apps.StatConfig',
    'obd.dashboards.administrators',
    'obd.dashboards.administrators.enviroments.apps.EnviromentConfig',
    'obd.dashboards.administrators.leagues.apps.LeagueConfig',
    'obd.dashboards.administrators.divisions.apps.DivisionConfig',
    'obd.dashboards.administrators.champions.apps.ChampionConfig',
    'cloudinary'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'obd.core.middleware.LimiteDeTentativasDeLogin',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'obd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'obd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#

# Config do banco: usa DATABASE_URL do Railway se existir, senão fallback SQLite local
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,
    )
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_TRUSTED_ORIGINS = [
    "https://obdsite-production.up.railway.app",
    "https://www.obdardos.com.br",
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATE_INPUT_FORMATS = ['%Y-%m-%d',
                      '%m/%d/%Y',
                      '%m/%d/%y']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email Configuration
ADMINS = [("OBD", "organizacaobrasileiradedardos@gmail.com")]
MANAGERS = ADMINS

cloudinary.config(
    cloud_name=config('CLOUDINARY_NAME'),
    api_key=config('CLOUDINARY_API_KEY'),
    api_secret=config('CLOUDINARY_API_SECRET'),
    secure=config('CLOUDINARY_SECURE')
)

# Scout settings
SCOUT_MONITOR = config('SCOUT_MONITOR')
SCOUT_KEY = config('SCOUT_KEY')
SCOUT_NAME = config('SCOUT_NAME')
# If you'd like to utilize Error Monitoring:
SCOUT_ERRORS_ENABLED = config('SCOUT_ERRORS')

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
}

# ---------------------------------------------------------------------------
# Segurança do tráfego (HTTPS)
#
# Tudo aqui vale só fora do DEBUG: em desenvolvimento o site roda em http, e ligar
# estas opções localmente impediria de entrar.
# ---------------------------------------------------------------------------

# O mais importante, e o que resolve um problema que já existia: atrás do proxy do
# Railway, o Django recebe o pedido em http e concluía que a conexão não era segura.
# Com isso, request.build_absolute_uri() montava endereços http:// — inclusive o link
# de recuperação de senha e o QR code do perfil. Este cabeçalho é o que o proxy usa
# para informar o protocolo original.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Os cookies de sessão e de CSRF deixam de trafegar em http.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Impede o navegador de adivinhar o tipo de um arquivo e tratá-lo como outra coisa.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Ao sair do site, o endereço completo da página de origem não é repassado.
SECURE_REFERRER_POLICY = 'same-origin'

# Redireciona http para https. Depende do cabeçalho lá de cima: sem ele o Django acha
# que todo pedido é http e redireciona em círculo, derrubando o site. Por isso existe a
# variável de ambiente — se algo der errado, basta pôr SECURE_SSL_REDIRECT=False no
# Railway e reiniciar, sem precisar de um novo deploy.
SECURE_SSL_REDIRECT = (not DEBUG) and config('SECURE_SSL_REDIRECT', default=True, cast=bool)

# HSTS: o navegador passa a recusar http neste domínio por conta própria, o que fecha a
# brecha do primeiro acesso, anterior ao redirecionamento.
#
# É a única opção daqui difícil de desfazer: o navegador guarda a instrução pelo prazo
# informado, e desligar no servidor não apaga o que já foi guardado. Por isso começa com
# 1 hora. Depois de algumas semanas sem problema, dá para subir para 31536000 (um ano)
# pela variável de ambiente.
#
# INCLUDE_SUBDOMAINS e PRELOAD ficam desligados de propósito: valeriam para todos os
# subdomínios e, no caso do preload, para listas embutidas nos navegadores — desfazer
# isso leva meses.
SECURE_HSTS_SECONDS = 0 if DEBUG else config('SECURE_HSTS_SECONDS', default=3600, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Mantido em SAMEORIGIN, e não em DENY: a tela de Documentos abre PDFs dentro de um
# iframe, e DENY quebraria o visualizador se o arquivo vier do próprio domínio.
X_FRAME_OPTIONS = 'SAMEORIGIN'