# Generated by Django 3.1.7 on 2021-03-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210327_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='268977-9', max_length=10, null=True, unique=True),
        ),
    ]
