# Generated by Django 3.1.7 on 2021-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210331_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='542748-0', max_length=10, null=True, unique=True),
        ),
    ]
