# Generated by Django 3.1.7 on 2021-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20210416_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='djangodbmodelsquery_utilsdeferredattribute-object-at-0x7f42fc238910-djangodbmodelsquery_utilsdeferredattribute-object-at-0x7f42fc238970-djangodbmodelsfieldscharfield', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='582302-5', max_length=10, null=True, unique=True),
        ),
    ]
