# Generated by Django 3.1.7 on 2021-04-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210419_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='278056-9', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='web-user-link', max_length=180),
            preserve_default=False,
        ),
    ]
