# Generated by Django 3.1.7 on 2021-05-04 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enviroments', '0004_auto_20210404_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.CharField(blank=True, default='Liga Online OBD', max_length=250)),
                ('add_info', models.CharField(blank=True, default='Para maiores informações consulte sempre as regras.', max_length=250)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('runoff', models.IntegerField(choices=[(1, 'Turno'), (2, 'Returno')], default=1)),
                ('phase', models.IntegerField(choices=[(0, 'Inscrição'), (1, 'Formação'), (2, 'Andamento'), (3, 'Playoffs'), (4, 'Encerrada'), (5, 'Anulada')], default=0)),
                ('scope', models.IntegerField(choices=[(0, 'Internacional'), (1, 'Continental'), (2, 'Nacional'), (3, 'Estadual'), (4, 'Municipal'), (5, 'Comemorativa')], default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enviroment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enviroments.enviroment')),
            ],
            options={
                'verbose_name': 'league',
                'verbose_name_plural': 'leagues',
                'ordering': ('created_at',),
            },
        ),
    ]
