# Generated by Django 3.1.7 on 2021-07-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20210601_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='phase',
            field=models.IntegerField(choices=[(0, 'Inscrição'), (1, 'Formação'), (2, 'Classificação'), (3, 'Playoffs'), (4, 'Encerrada'), (5, 'Anulada'), (6, 'Final')], default=0),
        ),
    ]
