# Generated by Django 3.1.7 on 2021-03-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210327_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_avg',
            new_name='bcmAvg',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_leg',
            new_name='bcmLeg',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_matches',
            new_name='bcmMatches',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_out',
            new_name='bcmOut',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_points',
            new_name='bcmPoints',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_ton',
            new_name='bcmTon',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_ton40',
            new_name='bcmTon40',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_ton80',
            new_name='bcmTon80',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='bcm_win',
            new_name='bcmWin',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='bcm_class',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='bcm_div',
        ),
        migrations.AddField(
            model_name='stat',
            name='bcmClass',
            field=models.IntegerField(choices=[(1, 'CLASS PRO'), (2, 'CLASS A'), (3, 'CLASS B'), (4, 'CLASS C'), (5, 'CLASS D'), (99, 'CLASS R')], default=99),
        ),
        migrations.AddField(
            model_name='stat',
            name='bcmDiv',
            field=models.IntegerField(choices=[(1, 'DIV 1'), (2, 'DIV 2'), (3, 'DIV 3'), (4, 'DIV 4'), (5, 'DIV 5'), (6, 'DIV 6'), (7, 'DIV 7'), (8, 'DIV 8'), (9, 'DIV 9'), (10, 'DIV 10'), (99, 'Formação')], default=10),
        ),
        migrations.AddField(
            model_name='stat',
            name='divAwinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='divBwinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='divCwinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='divDwinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='divOtherswinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='leagueParticipation',
            field=models.IntegerField(default=0),
        ),
    ]
