# Generated by Django 3.1.7 on 2021-03-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210330_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='bcm9DartsEnd',
            field=models.IntegerField(default=0),
        ),
    ]
