# Generated by Django 3.1.7 on 2021-03-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_stat_bcm9dartsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='leaguePerformance',
            field=models.CharField(default='XXXXXXXXXX', max_length=10),
        ),
    ]
