# Generated by Django 3.1.7 on 2021-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_stat_leagueperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='bcmTon70',
            field=models.IntegerField(default=0),
        ),
    ]
