# Generated by Django 3.1.7 on 2021-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_stat_bcmton70'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='best3da',
            field=models.FloatField(default=0),
        ),
    ]
