# Generated by Django 4.2.11 on 2025-11-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20210526_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
