# Generated by Django 4.2.11 on 2025-11-20 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(choices=[('statute', 'Estatuto'), ('rules', 'Regras'), ('regulation', 'Regulamento'), ('guide', 'Guia'), ('other', 'Outro')], default='other', max_length=50, verbose_name='Categoria')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Arquivo')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['category', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('event_date', models.DateTimeField(verbose_name='Data do Evento')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('event_type', models.CharField(choices=[('tournament', 'Torneio'), ('championship', 'Campeonato'), ('training', 'Treinamento'), ('meeting', 'Reunião'), ('other', 'Outro')], default='other', max_length=50, verbose_name='Tipo')),
                ('registration_link', models.URLField(blank=True, verbose_name='Link de Inscrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(verbose_name='Resumo')),
                ('link', models.URLField(verbose_name='Link da Notícia')),
                ('source', models.CharField(max_length=100, verbose_name='Fonte')),
                ('published_date', models.DateField(verbose_name='Data de Publicação')),
                ('image_url', models.URLField(blank=True, verbose_name='URL da Imagem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-published_date'],
            },
        ),
    ]
