# Generated by Django 4.2.11 on 2025-11-22 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Torneio')),
                ('source_url', models.URLField(verbose_name='URL da Fonte')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Torneio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Capturado em')),
            ],
            options={
                'verbose_name': 'Resultado de Torneio',
                'verbose_name_plural': 'Resultados de Torneios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTournamentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Nome do Jogador')),
                ('rank', models.IntegerField(verbose_name='Classificação')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Partidas Jogadas')),
                ('matches_won', models.IntegerField(default=0, verbose_name='Partidas Vencidas')),
                ('win_rate_matches', models.CharField(default='0%', max_length=10, verbose_name='Win Rate (Partidas)')),
                ('legs_played', models.IntegerField(default=0, verbose_name='Legs Jogados')),
                ('legs_won', models.IntegerField(default=0, verbose_name='Legs Vencidos')),
                ('legs_diff', models.IntegerField(default=0, verbose_name='Saldo de Legs')),
                ('win_rate_legs', models.CharField(default='0%', max_length=10, verbose_name='Win Rate (Legs)')),
                ('average_3_dart', models.FloatField(default=0.0, verbose_name='Média 3 Dardos')),
                ('average_1_dart', models.FloatField(default=0.0, verbose_name='Média 1 Dardo')),
                ('first_9_average', models.FloatField(default=0.0, verbose_name='Média Primeiros 9')),
                ('best_leg', models.IntegerField(default=0, verbose_name='Melhor Leg (Dardos)')),
                ('worst_leg', models.IntegerField(default=0, verbose_name='Pior Leg (Dardos)')),
                ('high_finish', models.IntegerField(default=0, verbose_name='Maior Fechamento')),
                ('count_100_plus', models.IntegerField(default=0, verbose_name='100+')),
                ('count_140_plus', models.IntegerField(default=0, verbose_name='140+')),
                ('count_170_plus', models.IntegerField(default=0, verbose_name='170+')),
                ('count_180', models.IntegerField(default=0, verbose_name='180s')),
                ('count_100_plus_finish', models.IntegerField(default=0, verbose_name='Fechamentos 100+')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.tournamentresult')),
            ],
            options={
                'verbose_name': 'Estatística de Jogador',
                'verbose_name_plural': 'Estatísticas de Jogadores',
                'ordering': ['rank'],
            },
        ),
    ]
