# Generated by Django 4.2.11 on 2026-08-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='prize_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Preencha apenas para torneios avulsos (ex: Tour Online). Etapas da Liga Nacional já têm a premiação somada via Order of Merit, não preencha aqui para evitar contar em dobro.', max_digits=10, null=True, verbose_name='Premiação Distribuída (R$)'),
        ),
    ]
