# Generated by Django 4.2.11 on 2026-08-26 00:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tournamentresult_prize_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem (upload)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL da Imagem (alternativa ao upload)'),
        ),
    ]
