# Generated by Django 4.2.11 on 2026-08-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_news_image_alter_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link da Notícia (fonte externa, opcional)'),
        ),
    ]
