# Generated by Django 4.2.11 on 2026-08-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, help_text='Preencha para notícias próprias da OBD (sem link de fonte externa). Vira a página que abre ao clicar na notícia no site.', verbose_name='Conteúdo Completo'),
        ),
    ]
