# Generated by Django 4.2.11 on 2026-09-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='in_progress',
            field=models.BooleanField(default=False, help_text='Marque enquanto a etapa ainda estiver em disputa. Enquanto marcada, o campeão não é registrado no Hall dos Campeões e a etapa não aparece na tela inicial. Desmarque quando a etapa terminar — o campeão é registrado nesse momento.', verbose_name='Etapa em andamento'),
        ),
    ]
