# Generated by Django 4.2.11 on 2026-09-10

from django.db import migrations, models

from obd.core.tournament_categories import CHOICES, OUTROS, adivinhar_categoria


def preencher_categorias(apps, schema_editor):
    """Dá um tipo inicial aos torneios que já existiam, chutando pelo nome.

    Sem isso, todos os torneios anteriores a esta migração cairiam em "Outros" e o
    administrador teria que classificar um por um. O chute acerta os nomes que a OBD
    usa hoje; o que ele errar é corrigido na tela de captura.
    """
    TournamentResult = apps.get_model('core', 'TournamentResult')
    for pk, nome in TournamentResult.objects.values_list('pk', 'name'):
        TournamentResult.objects.filter(pk=pk).update(category=adivinhar_categoria(nome))


def desfazer(apps, schema_editor):
    """Nada a desfazer: a coluna inteira sai quando a AddField é revertida."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tournamentresult_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='category',
            field=models.CharField(
                'Tipo de Torneio',
                max_length=20,
                choices=CHOICES,
                default=OUTROS,
                help_text='Define em qual bloco do Hall dos Campeões os campeões deste torneio '
                          'aparecem. Ao capturar, o site sugere um tipo pelo nome do torneio; '
                          'corrija aqui se a sugestão estiver errada.',
            ),
        ),
        migrations.RunPython(preencher_categorias, desfazer),
    ]
