# Generated by Django 4.2.11 on 2026-09-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tournament_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaDeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Usuário tentado')),
                ('ip', models.CharField(blank=True, db_index=True, max_length=45, verbose_name='Endereço de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Quando')),
            ],
            options={
                'verbose_name': 'tentativa de login',
                'verbose_name_plural': 'tentativas de login',
                'ordering': ('-criado_em',),
            },
        ),
    ]
