# Generated by Django 4.2.11 on 2026-09-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tentativa_de_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_link',
            field=models.URLField(blank=True, help_text='Preenchido, transforma a imagem principal num link: quem clicar nela vai para este endereço, numa aba nova. Vazio, a imagem continua sendo só imagem. Não confundir com "URL da Imagem", que é onde a foto está.', verbose_name='Link da Imagem Principal (opcional)'),
        ),
    ]
