# Generated by Django 4.2.11 on 2026-09-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_news_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_link',
            field=models.URLField(blank=True, help_text='Normalmente deixe vazio: clicar na imagem já abre a foto inteira. Preencha só quando a imagem precisar levar a outro lugar (um formulário de inscrição, por exemplo) — aí o clique vai para este endereço em vez de abrir a foto. Não confundir com "URL da Imagem", que é onde a foto está.', verbose_name='Link da Imagem Principal (opcional)'),
        ),
    ]
