from django import forms

class EnviromentForm(forms.Form):
    meritPmin = forms.IntegerField(label='Mín BCM Pro')
    meritAmin = forms.IntegerField(label='Mín BCM A')
    meritBmin = forms.IntegerField(label='Mín BCM B')
    meritCmin = forms.IntegerField(label='Mín BCM C')
    meritDmin = forms.IntegerField(label='Mín BCM D')
    meritRmin = forms.IntegerField(label='Máx BCM Rookie')
    meritTimeline = forms.IntegerField(label='Histórico (Dias)')
    meritChampionBonus = forms.IntegerField(label='Bônus Campeão')
    meritSecondBonus = forms.IntegerField(label='Bônus Vice Campeão')
    meritThirdBonus = forms.IntegerField(label='Bônus Terceiro Lugar')
    meritDivAPoints = forms.IntegerField(label='BCM Div A Pontos')
    meritDivBPoints = forms.IntegerField(label='BCM Div B Pontos')
    meritDivCPoints = forms.IntegerField(label='BCM Div C Pontos')
    meritDivOthersPoints = forms.IntegerField(label='BCM D+ Pontos')
    matchWinPoints = forms.IntegerField(label='Pontos por Triunfo')
    matchDrawPoints = forms.IntegerField(label='Pontos por Empate')
    leagueMaxPlayers = forms.IntegerField(label='Máx players por Divisão')
    leagueMinPlayers = forms.IntegerField(label='Mín players por Divisão')
    allowAutoBye = forms.IntegerField(label='Máx Ausência para AUTO WO')
    allowAutoPromo = forms.IntegerField(label='Permitir AUTO Promoção')
    allowAutoDemo = forms.IntegerField(label='Permitir AUTO Rebaixamento')
    leagueSubscriptionsEnds = forms.IntegerField(label='Prazo p/ Inscrições (Dias)')
    leagueAplayoffs = forms.BooleanField(label='Playoffs Div A', required=False)
    leagueBplayoffs = forms.BooleanField(label='Playoffs Div B', required=False)
    leagueCplayoffs = forms.BooleanField(label='Playoffs Div C', required=False)
    leagueOthersplayoffs = forms.BooleanField(label='Playoffs Div D+', required=False)
    leagueAMaxSet = forms.IntegerField(label='Div A Melhor de (Sets)')
    leagueBMaxSet = forms.IntegerField(label='Div B Melhor de (Sets)')
    leagueCMaxSet = forms.IntegerField(label='Div C Melhor de (Sets)')
    leagueOthersMaxSet = forms.IntegerField(label='Div D+ Melhor de (Sets)')
    leagueABestof = forms.IntegerField(label='Div A Melhor de (Legs)')
    leagueBBestof = forms.IntegerField(label='Div B Melhor de (Legs)')
    leagueCBestof = forms.IntegerField(label='Div C Melhor de (Legs)')
    leagueOthersBestof = forms.IntegerField(label='Div D+ Melhor de (Legs)')
    leagueAFirstTo = forms.IntegerField(label='Div A First To (Legs)')
    leagueBFirstTo = forms.IntegerField(label='Div B First To (Legs)')
    leagueCFirstTo = forms.IntegerField(label='Div C First To (Legs)')
    leagueOthersFirstTo = forms.IntegerField(label='Div D+ First To (Legs)')
    leagueAGameMode = forms.IntegerField(label='Div A Modalidade')
    leagueBGameMode = forms.IntegerField(label='Div B Modalidade')
    leagueCGameMode = forms.IntegerField(label='Div C Modalidade')
    leagueOthersGameMode = forms.IntegerField(label='Div D+ Modalidade')
    leagueAWinnerBy = forms.IntegerField(label='Div A Vitória (Set/Leg)')
    leagueBWinnerBy = forms.IntegerField(label='Div B Vitória (Set/Leg)')
    leagueCWinnerBy = forms.IntegerField(label='Div C Vitória (Set/Leg)')
    leagueOthersWinnerBy = forms.IntegerField(label='Div D+ Vitória (Set/Leg)')
