# Generated by Django 3.1.7 on 2021-03-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meritPmin', models.IntegerField(default=80)),
                ('meritAmin', models.IntegerField(default=70)),
                ('meritBmin', models.IntegerField(default=60)),
                ('meritCmin', models.IntegerField(default=50)),
                ('meritDmin', models.IntegerField(default=40)),
                ('meritRmin', models.IntegerField(default=30)),
                ('meritTimeline', models.IntegerField(default=361)),
                ('meritChampionBonus', models.IntegerField(default=150)),
                ('meritSecondBonus', models.IntegerField(default=100)),
                ('meritThirdBonus', models.IntegerField(default=50)),
                ('meritDivAPoints', models.IntegerField(default=15)),
                ('meritDivBPoints', models.IntegerField(default=9)),
                ('meritDivCPoints', models.IntegerField(default=5)),
                ('meritDivOthersPoints', models.IntegerField(default=3)),
                ('matchWinPoints', models.IntegerField(default=3)),
                ('matchDrawPoints', models.IntegerField(default=1)),
                ('leagueMaxPlayers', models.IntegerField(default=16)),
                ('leagueMinPlayers', models.IntegerField(default=8)),
                ('allowAutoBye', models.IntegerField(default=3)),
                ('allowAutoPromo', models.IntegerField(default=0)),
                ('allowAutoDemo', models.IntegerField(default=0)),
                ('leagueSubscriptionsEnds', models.IntegerField(default=31)),
                ('leagueAMaxSet', models.IntegerField(default=1)),
                ('leagueBMaxSet', models.IntegerField(default=1)),
                ('leagueCMaxSet', models.IntegerField(default=1)),
                ('leagueOthersMaxSet', models.IntegerField(default=1)),
                ('leagueABestof', models.IntegerField(default=14)),
                ('leagueBBestof', models.IntegerField(default=12)),
                ('leagueCBestof', models.IntegerField(default=10)),
                ('leagueOthersBestof', models.IntegerField(default=8)),
                ('leagueAFirstTo', models.IntegerField(default=8)),
                ('leagueBFirstTo', models.IntegerField(default=7)),
                ('leagueCFirstTo', models.IntegerField(default=6)),
                ('leagueOthersFirstTo', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'enviroment',
                'verbose_name_plural': 'enviroments',
                'ordering': ('-created_at',),
            },
        ),
    ]
