# Generated by Django 3.1.7 on 2021-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroments', '0003_auto_20210330_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviroment',
            name='leagueAGameMode',
            field=models.IntegerField(choices=[(1, 'SD 1001'), (2, 'DD 1001'), (3, 'SD 501'), (4, 'DD 501'), (5, 'SD 301'), (6, 'DD 301'), (7, 'SD 201'), (8, 'DD 201')], default=3),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueBGameMode',
            field=models.IntegerField(choices=[(1, 'SD 1001'), (2, 'DD 1001'), (3, 'SD 501'), (4, 'DD 501'), (5, 'SD 301'), (6, 'DD 301'), (7, 'SD 201'), (8, 'DD 201')], default=3),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueCGameMode',
            field=models.IntegerField(choices=[(1, 'SD 1001'), (2, 'DD 1001'), (3, 'SD 501'), (4, 'DD 501'), (5, 'SD 301'), (6, 'DD 301'), (7, 'SD 201'), (8, 'DD 201')], default=3),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueOthersGameMode',
            field=models.IntegerField(choices=[(1, 'SD 1001'), (2, 'DD 1001'), (3, 'SD 501'), (4, 'DD 501'), (5, 'SD 301'), (6, 'DD 301'), (7, 'SD 201'), (8, 'DD 201')], default=3),
        ),
    ]
