# Generated by Django 3.1.7 on 2021-07-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroments', '0005_auto_20210630_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviroment',
            name='leagueAplayoffs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueBplayoffs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueCplayoffs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueOthersplayoffs',
            field=models.BooleanField(default=False),
        ),
    ]
