# Generated by Django 3.1.7 on 2021-05-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ('created_at',), 'verbose_name': 'fixture', 'verbose_name_plural': 'fixtures'},
        ),
        migrations.AlterField(
            model_name='fixture',
            name='submited_on',
            field=models.DateField(blank=True),
        ),
    ]
