# Generated by Django 3.1.7 on 2021-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0005_remove_fixture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='on_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
