# Generated by Django 3.1.7 on 2021-06-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_auto_20210612_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='type',
            field=models.IntegerField(choices=[(0, 'NORMAL'), (2, 'FINAL'), (3, 'THIRD'), (4, 'BEST4'), (8, 'BEST8'), (16, 'BEST16'), (32, 'BEST32'), (64, 'BEST64'), (128, 'BEST128'), (256, 'BEST256'), (512, 'BEST512'), (1024, 'BEST1024'), (2048, 'BEST2048')], default=0),
        ),
    ]
