# Generated by Django 3.1.7 on 2021-07-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0008_fixture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='server',
            field=models.CharField(choices=[('WED', 'WEBCAMDARTS'), ('N01', 'NAKKA'), ('LID', 'LIDARTS'), ('DAC', 'DARTCONNECT'), ('GOP', 'GODARTSPRO'), ('PRE', 'PRESENCIAL'), ('OTH', 'OUTRO'), ('WO', 'WALKOVER')], default='OTH', max_length=250),
        ),
    ]
