# Generated by Django 3.1.7 on 2021-08-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0009_auto_20210725_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='photo',
            field=models.ImageField(default='https://res.cloudinary.com/hvnnhpdtd/image/upload/v1625926909/logo_black_gold_boa_2.png', upload_to=''),
        ),
    ]
