# Generated by Django 3.1.7 on 2021-05-26 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0002_auto_20210526_2318'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'FINALIZADO'), (2, 'CANCELADO')], default=0)),
                ('submited_by', models.CharField(blank=True, max_length=250)),
                ('submited_on', models.DateField(blank=True, verbose_name='Submited on')),
                ('link', models.CharField(blank=True, max_length=250, unique=True)),
                ('server', models.CharField(choices=[('WED', 'WEBCAMDARTS'), ('N01', 'NAKKA'), ('LID', 'LIDARTS'), ('DAC', 'DARTCONNECT'), ('GOP', 'GODARTSPRO'), ('PRE', 'PRESENCIAL'), ('OTH', 'OUTRO')], default='OTH', max_length=250)),
                ('validation', models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'VALIDADO'), (2, 'INVALIDO'), (3, 'CANCELADO')], default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fixture',
                'verbose_name_plural': 'fixtures',
                'ordering': ('created_at', 'submited_on'),
            },
        ),
    ]
