# Generated by Django 3.1.7 on 2021-05-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_auto_20210527_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='submited_on',
        ),
    ]
