# Generated by Django 3.1.7 on 2021-05-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_remove_fixture_submited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
