# Generated by Django 3.1.7 on 2021-05-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_auto_20210527_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='slug',
        ),
    ]
