# Generated by Django 4.2.11 on 2025-11-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0010_fixture_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='server',
            field=models.CharField(choices=[('N01', 'NAKKA'), ('LID', 'LIDARTS'), ('DAC', 'DARTCONNECT'), ('GOP', 'GODARTSPRO'), ('PRE', 'PRESENCIAL'), ('OTH', 'OUTRO'), ('WO', 'WALKOVER')], default='OTH', max_length=250),
        ),
    ]
