# Generated by Django 4.2.11 on 2026-09-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merits', '0005_delete_merit'),
        ('results', '0007_delete_result'),
        ('fixtures', '0011_alter_fixture_id_alter_fixture_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
