# Generated by Django 3.1.7 on 2021-05-04 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='Divisão OBD', max_length=250)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('formation', models.IntegerField(choices=[('1', 'Divisão A'), ('2', 'Divisão B'), ('3', 'Divisão C'), ('4', 'Divisão D'), ('5', 'Divisão E'), ('6', 'Divisão F'), ('7', 'Divisão G'), ('8', 'Divisão H'), ('9', 'Divisão I'), ('0', 'Formação')], default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'division',
                'verbose_name_plural': 'divisions',
                'ordering': ('created_at',),
            },
        ),
    ]
