# Generated by Django 3.1.7 on 2021-06-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_auto_20210526_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('-created_at',), 'verbose_name': 'division', 'verbose_name_plural': 'divisions'},
        ),
    ]
