# Generated by Django 3.1.7 on 2021-06-14 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisions', '0003_auto_20210601_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='winners', to=settings.AUTH_USER_MODEL),
        ),
    ]
