# Generated by Django 3.1.7 on 2021-07-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0005_auto_20210630_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='phase',
            field=models.IntegerField(choices=[(0, 'Inscrição'), (1, 'Formação'), (2, 'Andamento'), (3, 'Playoffs'), (4, 'Encerrada'), (5, 'Anulada'), (6, 'Final')], default=0),
        ),
    ]
