# Generated by Django 3.1.7 on 2021-07-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0006_division_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='phase',
            field=models.IntegerField(choices=[(0, 'A Definir'), (1, 'Em Formação'), (2, 'Em Andamento'), (3, 'Fase de Playoffs'), (4, 'Divisão Encerrada'), (5, 'Divisão Anulada'), (6, 'Fase Final')], default=0),
        ),
    ]
