# Generated by Django 3.1.7 on 2021-03-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviroment',
            options={'ordering': ('created_at',), 'verbose_name': 'enviroment', 'verbose_name_plural': 'enviroments'},
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueAGameMode',
            field=models.IntegerField(choices=[('1', 'SD 1001'), ('2', 'DD 1001'), ('3', 'SD 501'), ('4', 'DD 501'), ('5', 'SD 301'), ('6', 'DD 301')], default=3),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueAWinnerBy',
            field=models.IntegerField(choices=[('1', 'Por Sets'), ('2', 'Por Legs')], default=2),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueBGameMode',
            field=models.IntegerField(choices=[('1', 'SD 1001'), ('2', 'DD 1001'), ('3', 'SD 501'), ('4', 'DD 501'), ('5', 'SD 301'), ('6', 'DD 301')], default=3),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueBWinnerBy',
            field=models.IntegerField(choices=[('1', 'Por Sets'), ('2', 'Por Legs')], default=2),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueCGameMode',
            field=models.IntegerField(choices=[('1', 'SD 1001'), ('2', 'DD 1001'), ('3', 'SD 501'), ('4', 'DD 501'), ('5', 'SD 301'), ('6', 'DD 301')], default=3),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueCWinnerBy',
            field=models.IntegerField(choices=[('1', 'Por Sets'), ('2', 'Por Legs')], default=2),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueOthersGameMode',
            field=models.IntegerField(choices=[('1', 'SD 1001'), ('2', 'DD 1001'), ('3', 'SD 501'), ('4', 'DD 501'), ('5', 'SD 301'), ('6', 'DD 301')], default=3),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='leagueOthersWinnerBy',
            field=models.IntegerField(choices=[('1', 'Por Sets'), ('2', 'Por Legs')], default=2),
        ),
    ]
