# Generated by Django 3.1.7 on 2021-03-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroments', '0002_auto_20210330_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviroment',
            name='leagueAGameMode',
            field=models.IntegerField(choices=[(1, 'SD 1001'), (2, 'DD 1001'), (3, 'SD 501'), (4, 'DD 501'), (5, 'SD 301'), (6, 'DD 301')], default=3),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueAWinnerBy',
            field=models.IntegerField(choices=[(1, 'Por Sets'), (2, 'Por Legs')], default=2),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueBGameMode',
            field=models.IntegerField(choices=[(1, 'SD 1001'), (2, 'DD 1001'), (3, 'SD 501'), (4, 'DD 501'), (5, 'SD 301'), (6, 'DD 301')], default=3),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueBWinnerBy',
            field=models.IntegerField(choices=[(1, 'Por Sets'), (2, 'Por Legs')], default=2),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueCGameMode',
            field=models.IntegerField(choices=[(1, 'SD 1001'), (2, 'DD 1001'), (3, 'SD 501'), (4, 'DD 501'), (5, 'SD 301'), (6, 'DD 301')], default=3),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueCWinnerBy',
            field=models.IntegerField(choices=[(1, 'Por Sets'), (2, 'Por Legs')], default=2),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueOthersGameMode',
            field=models.IntegerField(choices=[(1, 'SD 1001'), (2, 'DD 1001'), (3, 'SD 501'), (4, 'DD 501'), (5, 'SD 301'), (6, 'DD 301')], default=3),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='leagueOthersWinnerBy',
            field=models.IntegerField(choices=[(1, 'Por Sets'), (2, 'Por Legs')], default=2),
        ),
    ]
