# Generated by Django 3.1.7 on 2021-06-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enviroments', '0004_auto_20210404_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviroment',
            options={'ordering': ('-created_at',), 'verbose_name': 'enviroment', 'verbose_name_plural': 'enviroments'},
        ),
    ]
