# Generated by Django 3.1.7 on 2021-09-04 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0007_auto_20210707_2055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0004_auto_20210707_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'Pontos Corridos'), (2, 'Mata-Mata'), (3, 'Copa')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='divisions.division')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leagues.league')),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='p2', to=settings.AUTH_USER_MODEL)),
                ('p3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='p3', to=settings.AUTH_USER_MODEL)),
                ('p4', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='p4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'champion',
                'verbose_name_plural': 'champions',
                'ordering': ('-created_at',),
            },
        ),
    ]
