# Generated by Django 3.1.7 on 2021-03-25 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcm_class', models.CharField(default='R', max_length=2)),
                ('bcm_div', models.CharField(default='R', max_length=2)),
                ('bcm_points', models.FloatField(default=0)),
                ('bcm_avg', models.FloatField(default=26)),
                ('bcm_matches', models.IntegerField(default=0)),
                ('bcm_win', models.IntegerField(default=0)),
                ('bcm_ton', models.IntegerField(default=0)),
                ('bcm_ton40', models.IntegerField(default=0)),
                ('bcm_ton80', models.IntegerField(default=0)),
                ('bcm_leg', models.IntegerField(default=0)),
                ('bcm_out', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stat',
                'verbose_name_plural': 'stats',
                'ordering': ('-created_at',),
            },
        ),
    ]
