# Generated by Django 3.1.7 on 2021-03-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='bcm_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='bcm_class',
            field=models.IntegerField(choices=[('1', 'CLASS PRO'), ('2', 'CLASS A'), ('3', 'CLASS B'), ('4', 'CLASS C'), ('5', 'CLASS D'), ('0', 'CLASS R')], default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='bcm_div',
            field=models.IntegerField(choices=[('1', 'DIV 1'), ('2', 'DIV 2'), ('3', 'DIV 3'), ('4', 'DIV 4'), ('5', 'DIV 5'), ('6', 'DIV 6'), ('7', 'DIV 7'), ('8', 'DIV 8'), ('9', 'DIV 9'), ('10', 'DIV 10'), ('99', 'Formação')], default=10),
        ),
    ]
