# Generated by Django 3.1.7 on 2021-05-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_stat_best3da'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='bcmDiv',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H'), (9, 'I'), (10, 'J'), (0, 'Formação')], default=10),
        ),
    ]
