# Generated by Django 3.1.7 on 2021-03-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-created_at',), 'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='country',
            field=models.CharField(max_length=40, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='nickname',
            field=models.CharField(max_length=40, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='password',
            field=models.CharField(max_length=99, verbose_name='Password'),
        ),
    ]
