# Generated by Django 3.1.7 on 2021-03-23 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=40, null=True)),
                ('nickname', models.CharField(blank=True, max_length=11, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=180, null=True)),
                ('country', models.CharField(blank=True, default='Brasil', max_length=40)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('darts', models.CharField(blank=True, max_length=40, null=True)),
                ('site', models.CharField(blank=True, max_length=80, null=True)),
                ('facebook', models.CharField(blank=True, max_length=80, null=True)),
                ('twitter', models.CharField(blank=True, max_length=80, null=True)),
                ('webcamdarts', models.CharField(blank=True, max_length=40, null=True)),
                ('nakka', models.CharField(blank=True, max_length=40, null=True)),
                ('lidarts', models.CharField(blank=True, max_length=40, null=True)),
                ('dartconnect', models.CharField(blank=True, max_length=40, null=True)),
                ('godartspro', models.CharField(blank=True, max_length=40, null=True)),
                ('brazilfederation', models.BooleanField(default=False)),
                ('latamfederation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
