# Generated by Django 3.1.7 on 2021-04-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20210416_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='646227-7', max_length=10, null=True, unique=True),
        ),
    ]
