# Generated by Django 3.1.7 on 2021-04-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210421_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created_at',), 'permissions': [('has_admin_role', 'Administrador'), ('has_player_role', 'Jogador'), ('can_play_league', 'Habilitado para jogar na Liga')], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='436897-8', max_length=10, null=True, unique=True),
        ),
    ]
