# Generated by Django 3.1.7 on 2021-04-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210421_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='967607-3', max_length=10, null=True, unique=True),
        ),
    ]
