# Generated by Django 3.1.7 on 2021-07-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20210710_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='https://res.cloudinary.com/hvnnhpdtd/image/upload/v1625926909/logo_black_gold_boa_2.png', upload_to=''),
        ),
    ]
