# Generated by Django 4.2.11 on 2025-11-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20210710_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='webcamdarts',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
