# Generated by Django 4.2.11 on 2025-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_remove_webcamdarts_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dartconnect',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='godartspro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lidarts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='localfederation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationalfederation',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/static/media/defaults/default_profile.png', upload_to=''),
        ),
    ]
