# Generated by Django 4.2.11 on 2026-02-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_remove_external_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/static/media/logos/Logo_OBD_3.jpeg', upload_to=''),
        ),
    ]
