# Generated by Django 4.2.11 on 2026-09-12 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_profile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApelidoN01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=80, unique=True, verbose_name='Apelido no N01')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apelidos_n01', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'apelido no N01',
                'verbose_name_plural': 'apelidos no N01',
                'ordering': ('apelido',),
            },
        ),
    ]
