# Generated by Django 3.1.7 on 2021-03-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210325_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
