# Generated by Django 3.1.7 on 2021-03-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210325_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='485485-1', max_length=10, null=True, unique=True),
        ),
    ]
