# Generated by Django 3.1.7 on 2021-03-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210330_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='267133-6', max_length=10, null=True, unique=True),
        ),
    ]
