# Generated by Django 3.1.7 on 2021-04-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20210420_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created_at',), 'permissions': [('has_admin_role', 'Administrador OBD'), ('has_player_role', 'Jogador OBD'), ('can_play_league', 'Habilitado/Ativo')], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='544117-9', max_length=10, null=True, unique=True),
        ),
    ]
