# Generated by Django 3.1.7 on 2021-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210421_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='brazilfederation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latamfederation',
        ),
        migrations.AddField(
            model_name='profile',
            name='localfederation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationalfederation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Bio', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='dartconnect',
            field=models.CharField(blank=True, default='123456', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='darts',
            field=models.CharField(blank=True, default='Darts Model', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='facebook id', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='godartspro',
            field=models.CharField(blank=True, default='123456', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='lidarts',
            field=models.CharField(blank=True, default='123456', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='nakka',
            field=models.CharField(blank=True, default='123456', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='The Kabra', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='123456-7', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.CharField(blank=True, default='www', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, default='123456-7-player-name', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='State', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default='Twitter', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='webcamdarts',
            field=models.CharField(blank=True, default='The Kabra', max_length=40),
            preserve_default=False,
        ),
    ]
