# Generated by Django 3.1.7 on 2021-07-07 20:55

import brasilonline.dashboards.players.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210424_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=brasilonline.dashboards.players.profiles.models.image_file_path, validators=[brasilonline.dashboards.players.profiles.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dartconnect',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='darts',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='godartspro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lidarts',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nakka',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webcamdarts',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
