# Generated by Django 3.1.7 on 2021-07-08 01:36

import brasilonline.dashboards.players.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20210707_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/media/logo.jpeg', upload_to=brasilonline.dashboards.players.profiles.models.image_file_path, validators=[brasilonline.dashboards.players.profiles.models.validate_file_extension]),
        ),
    ]
