# Generated by Django 3.1.7 on 2021-07-08 03:55

import brasilonline.dashboards.players.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20210708_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='logo.jpeg', upload_to=brasilonline.dashboards.players.profiles.models.image_file_path),
        ),
    ]
