# Generated by Django 3.1.7 on 2021-07-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20210708_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='logo.jpeg', upload_to=''),
        ),
    ]
