# Generated by Django 3.1.7 on 2021-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20210710_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='logos/standard_logo.png', upload_to=''),
        ),
    ]
